# Generated by Django 4.2.15 on 2024-09-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_adminpermissionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpermissionmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_customize_medical_tests',
            field=models.BooleanField(default=False, verbose_name='إضافة تخصيص الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_home_visit',
            field=models.BooleanField(default=False, verbose_name='إضافة زيارة منزلية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_medical_tests',
            field=models.BooleanField(default=False, verbose_name='إضافة الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_normal_visit',
            field=models.BooleanField(default=False, verbose_name='إضافة زيارة عادية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_patient',
            field=models.BooleanField(default=False, verbose_name='إضافة مريض'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='إضافة تقارير الزيارات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_customize_medical_tests',
            field=models.BooleanField(default=False, verbose_name='حذف تخصيص الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_home_visit',
            field=models.BooleanField(default=False, verbose_name='حذف زيارة منزلية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_medical_tests',
            field=models.BooleanField(default=False, verbose_name='حذف الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_normal_visit',
            field=models.BooleanField(default=False, verbose_name='حذف زيارة عادية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_patient',
            field=models.BooleanField(default=False, verbose_name='حذف مريض'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='حذف تقارير الزيارات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='download_medical_tests',
            field=models.BooleanField(default=False, verbose_name='تحميل الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='download_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='تحميل تقارير الزيارات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_customize_medical_tests',
            field=models.BooleanField(default=False, verbose_name='تعديل تخصيص الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_home_visit',
            field=models.BooleanField(default=False, verbose_name='تعديل زيارة منزلية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_medical_tests',
            field=models.BooleanField(default=False, verbose_name='تعديل الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_normal_visit',
            field=models.BooleanField(default=False, verbose_name='تعديل زيارة عادية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_patient',
            field=models.BooleanField(default=False, verbose_name='تعديل مريض'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='تعديل تقارير الزيارات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_customize_medical_tests',
            field=models.BooleanField(default=False, verbose_name='عرض تخصيص الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_home_visit',
            field=models.BooleanField(default=False, verbose_name='عرض الزيارات المنزلية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_medical_tests',
            field=models.BooleanField(default=False, verbose_name='عرض الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_normal_visit',
            field=models.BooleanField(default=False, verbose_name='عرض الزيارات العادية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_patient',
            field=models.BooleanField(default=False, verbose_name='عرض المرضى'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='عرض تقارير الزيارات الطبية'),
        ),
    ]
