# Generated by Django 4.2.15 on 2024-09-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_adminpermissionmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='show_index',
            field=models.BooleanField(default=False, verbose_name='عرض اللوحة الرئيسية'),
        ),
    ]
