# Generated by Django 4.2.15 on 2024-09-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_adminpermissionmodel_show_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='view_medical_tests',
            field=models.BooleanField(default=False, verbose_name='عرض الفحوصات الطبية'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='view_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='عرض تقارير الزيارات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_customize_medical_tests',
            field=models.BooleanField(default=False, verbose_name='ادارة تخصيص الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_home_visit',
            field=models.BooleanField(default=False, verbose_name='ادارة الزيارات المنزلية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_index',
            field=models.BooleanField(default=False, verbose_name='ادارة اللوحة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_medical_tests',
            field=models.BooleanField(default=False, verbose_name='ادارة الفحوصات الطبية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_normal_visit',
            field=models.BooleanField(default=False, verbose_name='ادارة الزيارات العادية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_patient',
            field=models.BooleanField(default=False, verbose_name='ادارة المرضى'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='ادارة تقارير الزيارات الطبية'),
        ),
    ]
