# Generated by Django 4.2.15 on 2024-09-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_adminpermissionmodel_view_medical_tests_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomizeMedicalTestsModel',
        ),
    ]
