# Generated by Django 4.2.15 on 2024-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_delete_customizemedicaltestsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='add_admin',
            field=models.BooleanField(default=False, verbose_name='ادارة المرضى'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='delete_admin',
            field=models.BooleanField(default=False, verbose_name='ادارة المرضى'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='edit_admin',
            field=models.BooleanField(default=False, verbose_name='ادارة المرضى'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='show_admin',
            field=models.BooleanField(default=False, verbose_name='ادارة المرضى'),
        ),
    ]
