# Generated by Django 4.2.15 on 2024-09-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_adminpermissionmodel_add_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_admin',
            field=models.BooleanField(default=False, verbose_name='Add administrators'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_customize_medical_tests',
            field=models.BooleanField(default=False, verbose_name='Add custom medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_home_visit',
            field=models.BooleanField(default=False, verbose_name='Add home visit'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_medical_tests',
            field=models.BooleanField(default=False, verbose_name='Add medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_normal_visit',
            field=models.BooleanField(default=False, verbose_name='Add normal visit'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_patient',
            field=models.BooleanField(default=False, verbose_name='Add patient'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='Add medical visit reports'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_admin',
            field=models.BooleanField(default=False, verbose_name='Delete administrators'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_customize_medical_tests',
            field=models.BooleanField(default=False, verbose_name='Delete custom medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_home_visit',
            field=models.BooleanField(default=False, verbose_name='Delete home visit'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_medical_tests',
            field=models.BooleanField(default=False, verbose_name='Delete medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_normal_visit',
            field=models.BooleanField(default=False, verbose_name='Delete normal visit'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_patient',
            field=models.BooleanField(default=False, verbose_name='Delete patient'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='Delete medical visit reports'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='download_medical_tests',
            field=models.BooleanField(default=False, verbose_name='Download medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='download_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='Download medical visit reports'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_admin',
            field=models.BooleanField(default=False, verbose_name='Edit administrators'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_customize_medical_tests',
            field=models.BooleanField(default=False, verbose_name='Edit custom medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_home_visit',
            field=models.BooleanField(default=False, verbose_name='Edit home visit'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_medical_tests',
            field=models.BooleanField(default=False, verbose_name='Edit medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_normal_visit',
            field=models.BooleanField(default=False, verbose_name='Edit normal visit'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_patient',
            field=models.BooleanField(default=False, verbose_name='Edit patient'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_settings',
            field=models.BooleanField(default=False, verbose_name='Edit settings'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='Edit medical visit reports'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is the administrator enabled'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_admin',
            field=models.BooleanField(default=False, verbose_name='Manage administrators'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_customize_medical_tests',
            field=models.BooleanField(default=False, verbose_name='Manage custom medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_home_visit',
            field=models.BooleanField(default=False, verbose_name='Manage home visits'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_index',
            field=models.BooleanField(default=False, verbose_name='Manage the main panel'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_medical_tests',
            field=models.BooleanField(default=False, verbose_name='Manage medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_normal_visit',
            field=models.BooleanField(default=False, verbose_name='Manage normal visits'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_patient',
            field=models.BooleanField(default=False, verbose_name='Manage patients'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='Manage medical visit reports'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='view_medical_tests',
            field=models.BooleanField(default=False, verbose_name='View medical tests'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='view_visit_medical_report',
            field=models.BooleanField(default=False, verbose_name='View medical visit reports'),
        ),
    ]
