# Generated by Django 4.2.15 on 2024-08-27 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(null=True, verbose_name='العمر')),
                ('birth_date', models.DateField(null=True, verbose_name='العمر')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(blank=True, choices=[('0', 'ادمين'), ('2', 'موظف'), ('3', 'مريض')], max_length=255, null=True, verbose_name='نو الملف الشخصي')),
                ('account_alias_name', models.CharField(blank=True, choices=[('0', 'موظف'), ('2', 'طبيب'), ('3', 'مختبر')], max_length=255, null=True, verbose_name='نو الملف الشخصي')),
                ('phone', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVistorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_pay_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_home_visit', models.BooleanField()),
                ('visit_distance', models.CharField(choices=[('1', '0-30 KM'), ('2', '30-60 KM')], max_length=254)),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_visit', models.TextField()),
                ('clinical_examination', models.TextField()),
                ('treatment', models.TextField()),
                ('diagnosis', models.CharField(max_length=254)),
                ('recommendations', models.TextField()),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistor_doctor', to='accounts.patientvistormodel')),
                ('vistor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistor', to='accounts.patientvistormodel')),
            ],
        ),
    ]
