# Generated by Django 4.2.15 on 2024-08-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'ذكر'), ('2', 'انثى')], max_length=255, null=True),
        ),
    ]
