# Generated by Django 4.2.15 on 2024-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='العمر'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.IntegerField(null=True, verbose_name='العمر'),
        ),
    ]
