# Generated by Django 4.2.15 on 2024-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvistormodel',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patientvistormodel',
            name='visit_distance',
            field=models.CharField(blank=True, choices=[('1', '0-30 KM'), ('2', '30-60 KM')], max_length=254, null=True),
        ),
    ]
