# Generated by Django 4.2.15 on 2024-08-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patientvistormodel_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvistormodel',
            name='is_home_visit',
            field=models.BooleanField(default=False),
        ),
    ]
