# Generated by Django 4.2.15 on 2024-08-28 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_alter_patientvistormodel_is_home_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalreportmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistor_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
