# Generated by Django 4.2.15 on 2024-09-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_patientvistormodel_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalreportmodel',
            name='oxygen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalreportmodel',
            name='pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalreportmodel',
            name='pulse',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalreportmodel',
            name='sugar',
            field=models.IntegerField(null=True),
        ),
    ]
