# Generated by Django 4.2.15 on 2024-09-04 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_adminpermissionmodel_user_and_more'),
        ('accounts', '0009_patientmedicalreportmodel_oxygen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminpermissionmodel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_alias_name',
            field=models.CharField(blank=True, choices=[('0', 'موظف'), ('2', 'طبيب'), ('3', 'محلل')], max_length=255, null=True, verbose_name='اسم المستعار للملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'ذكر'), ('2', 'انثى')], max_length=255, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('0', 'ادمين'), ('2', 'موظف'), ('3', 'مريض')], max_length=255, null=True, verbose_name='نوع الملف الشخصي'),
        ),
    ]
