# Generated by Django 4.2.15 on 2024-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_patientmedicalreportmodel_custom_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalreportmodel',
            name='custom_diagnosis',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
