# Generated by Django 4.2.15 on 2024-09-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_adminpermissionmodel_view_medical_tests_and_more'),
        ('accounts', '0012_alter_patientmedicalreportmodel_custom_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='patient_profile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_alias_name',
            field=models.CharField(blank=True, choices=[('0', 'פקיד'), ('2', 'طبيب'), ('3', 'לבורנט')], max_length=255, null=True, verbose_name='اسم المستعار للملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'זכר'), ('2', 'נקבה')], max_length=255, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('0', 'מנהל'), ('2', 'פקיד'), ('3', 'מטופל')], max_length=255, null=True, verbose_name='نوع الملف الشخصي'),
        ),
        migrations.CreateModel(
            name='HospitalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('number', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('lang', models.CharField(choices=[('ar', 'العربية'), ('he', 'עִברִית'), ('en', 'English'), ('ro', 'Românește'), ('de', 'Deutsch')], default='en', max_length=254)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.uploadimagemodel')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hospitalsmodel'),
        ),
    ]
