# Generated by Django 4.2.15 on 2024-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_userprofile_patient_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsmodel',
            name='img_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalsmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m'),
        ),
    ]
