# Generated by Django 4.2.15 on 2024-09-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_hospitalsmodel_img_base64_alter_hospitalsmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hospital_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hospitalsmodel'),
        ),
    ]
