# Generated by Django 4.2.15 on 2024-09-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userprofile_hospital_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hospital_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hospitalsmodel'),
        ),
    ]
