# Generated by Django 4.2.15 on 2024-09-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_userprofile_address_alter_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeMedicalTestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('data', models.JSONField(null=True)),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('hospital_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hospitalsmodel')),
            ],
        ),
    ]
