# Generated by Django 4.2.15 on 2024-09-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customizemedicaltestsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalsmodel',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hospitalsmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='hospitalsmodel',
            name='img_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='hospitalsmodel',
            name='lang',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('de', 'Deutsch'), ('he', 'עִברִית'), ('ro', 'Românește')], default='en', max_length=254, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='hospitalsmodel',
            name='name',
            field=models.CharField(max_length=254, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hospitalsmodel',
            name='number',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_alias_name',
            field=models.CharField(blank=True, choices=[('0', 'Employee'), ('2', 'Doctor'), ('3', 'Analyst'), ('3', 'Reporter')], max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=255, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.IntegerField(null=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('0', 'Admin'), ('2', 'Employee'), ('3', 'Patient')], max_length=255, null=True, verbose_name='نوع الملف الشخصي'),
        ),
    ]
