# Generated by Django 4.2.15 on 2024-09-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_hospitalsmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
