# Generated by Django 4.2.15 on 2024-09-17 13:25

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_userprofile_active_messenger_userprofile_is_in_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('subtitle', models.TextField(verbose_name='العنوان الفرعي')),
                ('ico', models.ImageField(blank=True, upload_to='subscription/ico/')),
                ('Theem', models.CharField(choices=[('btn btn-primary', 'primary'), ('btn btn-secondary', 'secondary'), ('btn btn-success', 'success'), ('btn btn-danger', 'danger'), ('btn btn-warning', 'warning'), ('btn btn-info', 'info'), ('btn btn-light', 'light'), ('btn btn-dark', 'dark')], max_length=255, null=True, verbose_name='الثيم')),
                ('is_default_Subscription', models.BooleanField(default=False, verbose_name='هل هذه الباقة الافتراضية عند التسجيل')),
                ('number_of_days', models.IntegerField(default=30, verbose_name='عدد الأيام')),
                ('set_defult_price', models.BooleanField(default=False, verbose_name='عرض الباقة في الدول الغير مخصصة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
                ('currency', models.CharField(choices=[('SAR', 'ريال سعودي'), ('USD', 'دولار'), ('EUR', 'يورو')], default='USD', max_length=250, null=True, verbose_name='العملة')),
                ('number_of_patient', models.IntegerField(default=1, verbose_name='عدد المرضى')),
                ('number_of_local_visit', models.IntegerField(default=1, verbose_name='عدد الزيارات المحلية')),
                ('number_of_home_visit', models.IntegerField(default=1, verbose_name='عدد الزيارات المنزلية')),
                ('hosptial_storage_size_mb', models.IntegerField(default=1, verbose_name='حجم مساحة تخزين المشفى')),
                ('number_of_visit_medical_reports', models.IntegerField(default=1, verbose_name='عدد اضافة التقارير الطبية')),
                ('number_of_customize_medical_tests', models.IntegerField(default=1, verbose_name='عدد نماذج تخصيص التحاليل')),
                ('number_of_medical_tests_reports', models.IntegerField(default=1, verbose_name='عدد تقارير التحاليل')),
                ('number_of_manager', models.IntegerField(default=1, verbose_name='تحديد عدد المدراء')),
                ('one_to_one_chat', models.BooleanField(default=False, verbose_name='دردشة بين المدراء والموظفين')),
                ('extract_patient_info', models.BooleanField(default=False, verbose_name='استخراج بيانات المرضى (excel, csv, html json)')),
                ('live_chat_with_support', models.BooleanField(default=False, verbose_name='دردشة مباشرة مع الدعم الفني')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='تاريخ الانشاء')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(default=accounts.models.payOrderCodeGen, max_length=250, null=True, verbose_name='الاسم الثلاثي')),
                ('transactionNo', models.CharField(max_length=250, null=True)),
                ('is_buyed', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionsmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usersubscriptionmodel'),
        ),
    ]
