# Generated by Django 4.2.15 on 2024-09-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_userprofile_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionmodel',
            name='currency',
            field=models.CharField(choices=[('SAR', 'ريال سعودي'), ('USD', 'دولار'), ('EUR', 'يورو')], default='USD', max_length=250, null=True, verbose_name='العملة'),
        ),
    ]
