# Generated by Django 4.2.15 on 2024-09-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_subscriptionsmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsmodel',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='هل الاشتراك قابل للشراء'),
        ),
    ]
