# Generated by Django 4.2.15 on 2024-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_subscriptionsmodel_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionmodel',
            name='plan_scope',
            field=models.CharField(choices=[('1', 'Monthly'), ('2', 'Yearly')], max_length=254, null=True),
        ),
    ]
