# Generated by Django 4.2.15 on 2025-02-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_usersubscriptionmodel_plan_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalreportmodel',
            name='oxygen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalreportmodel',
            name='pressure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalreportmodel',
            name='pulse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalreportmodel',
            name='sugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
